/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DevOps02;

import com.mitchtalmadge.asciidata.graph.ASCIIGraph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        String graph = ASCIIGraph.fromSeries(new double[] {1.0,2.0,3.0,10.0,7.0,9.0,5.0,4.0}).plot();

        System.out.println(graph);

    }
}

